# Generated by Django 3.1.5 on 2021-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_topic', models.CharField(max_length=50, verbose_name='任务名称')),
                ('task_id', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('task_note', models.CharField(max_length=100, verbose_name='任务说明')),
                ('task_origin', models.CharField(max_length=150, verbose_name='任务来源')),
                ('aim_value', models.CharField(max_length=50, verbose_name='目标值')),
                ('deadline', models.DateField(verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '年度任务',
                'verbose_name_plural': '年度任务',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_topic', models.CharField(max_length=50, verbose_name='工作事项')),
                ('todo_note', models.CharField(blank=True, max_length=100, verbose_name='工作要求及交付物')),
                ('predict_work', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='预计工作量')),
                ('evaluate_factor', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='折算系数')),
                ('maturity', models.CharField(blank=True, choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='0%', max_length=5, verbose_name='成熟度')),
                ('real_work', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='实际工作量')),
                ('complete_note', models.TextField(blank=True, max_length=150, verbose_name='完成情况说明')),
                ('deadline', models.DateField(verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '工作包',
                'verbose_name_plural': '工作包',
                'ordering': ['deadline'],
            },
        ),
    ]
