# Generated by Django 3.1.5 on 2021-03-05 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20210304_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='aim_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='目标值'),
        ),
        migrations.AlterField(
            model_name='task',
            name='leader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL, verbose_name='主管领导'),
        ),
        migrations.AlterField(
            model_name='task',
            name='principal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='principal', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='任务说明'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_origin',
            field=models.CharField(blank=True, max_length=150, verbose_name='任务来源'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='evaluate_factor',
            field=models.DecimalField(blank=True, decimal_places=1, default='1', max_digits=5, verbose_name='折算系数'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='predict_work',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='预计工作量'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='related_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_task', to='tasks.task', verbose_name='年度任务'),
        ),
    ]
