# Generated by Django 3.1.5 on 2021-03-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210305_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='编号'),
        ),
    ]
