# Generated by Django 3.1.5 on 2021-02-01 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_auto_20210130_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='main_executor',
        ),
        migrations.AddField(
            model_name='todo',
            name='main_executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_executor', to=settings.AUTH_USER_MODEL, verbose_name='承/督办人'),
        ),
    ]
