# Generated by Django 3.1.5 on 2021-03-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210305_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='predict_work',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='预计工作量'),
        ),
    ]
