# Generated by Django 3.1.5 on 2021-03-05 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_auto_20210305_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='sub_executor',
            field=models.ManyToManyField(blank=True, related_name='sub_executor', to=settings.AUTH_USER_MODEL, verbose_name='协办人'),
        ),
    ]
