# Generated by Django 3.1.5 on 2021-01-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210129_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskproperty',
            name='own_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='所属部门'),
        ),
    ]
