# Generated by Django 3.1.5 on 2021-02-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210201_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markvalue',
            options={'verbose_name': '评价等级考核系数', 'verbose_name_plural': '评价等级考核系数'},
        ),
        migrations.AlterModelOptions(
            name='qualitymark',
            options={'verbose_name': '评价等级定义', 'verbose_name_plural': '评价等级定义'},
        ),
        migrations.AlterField(
            model_name='markvalue',
            name='mark_value',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='评价等级考核系数'),
        ),
        migrations.AlterField(
            model_name='qualitymark',
            name='mark_name',
            field=models.CharField(max_length=10, verbose_name='评价等级定义'),
        ),
    ]
